platform :ios, '10.0'
  use_frameworks!
  def shared_pods
  pod 'D2PDatePicker'
  pod 'Charts'
  pod 'ChartsRealm'
  pod 'SwiftyBluetooth'
  pod 'RealmSwift' 
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'AlamofireNetworkActivityLogger'
  pod 'SwiftyJSON'
  pod 'Kingfisher', '~> 4.0'
  pod 'MBProgressHUD'
  pod 'ReachabilitySwift', '~> 3'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'IQKeyboardManagerSwift', '5.0.0' 
  pod 'DateTimePicker'
  pod 'DatePickerDialog'
#  pod 'SwiftWebVC'
end

target 'Water Energy Tracker' do
   shared_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == '<insert target name of your pod here>'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
